export const SET_LOADING = 'MEMBERS/SET_LOADING';
export const SET_MEMBERS = 'MEMBERS/SET_MEMBERS';
export const SET_MEMBER = 'MEMBERS/SET_MEMBER';
export const SET_MODAL = 'MEMBERS/SET_MODAL';
export const SET_NAME = 'MEMBERS/SET_NAME';
export const SET_TITLE = 'MEMBERS/SET_TITLE';
export const SET_HIDDEN = 'MEMBERS/SET_HIDDEN';
export const SET_DISABLED = 'MEMBERS/SET_DISABLED';
export const SET_REGISTER = 'MEMBERS/SET_REGISTER';

export const SET_STATUS = 'MEMBERS/SET_STATUS';
export const SET_SHOW_STATUS = 'MEMBERS/SET_SHOW_STATUS';
export const SET_STATUS_MESSAGE = 'MEMBERS/SET_STATUS_MESSAGE';
